updated the readme file to update the installation instruction for a …
pritunl/pritunl-client pull request #69
Opened 2022-12-06 10:44 UTC by arunmastermind

…specific version

2022-12-06 10:45 UTC, arunmastermind commented
Updated Readme file to provide the instruction to install a specific version

2023-02-23 07:09 UTC, ImBIOS commented
Thanks

2023-02-24 07:06 UTC, arunmastermind commented
> Thanks

can we get this PR merged?

2023-02-24 07:45 UTC, ImBIOS requested changes

2023-02-24 07:45 UTC, ImBIOS commented on README.md
> +# Installing Specific Version
Please ue heading 2 (`##`) here

2023-02-24 07:57 UTC, arunmastermind commented
changes made as requested

2023-02-24 20:32 UTC, zachhuff386 commented
The script will already install the latest released version, it doesn't pull code directly from the repository. This is the only version I want recommended to install.

2023-02-24 20:32 UTC, closed without merging